#!/bin/bash
# By Mohammad Afaneh (2019), Afaneh92 @ XDA Developers.
# Source code https://github.com/osm0sis/Android-Image-Kitchen/tree/AIK-Linux
#
# Rename AIK_Linux_menu to menu
# sh ./menu and press "d" to downlad required files
#
# AIK-Linux menu v0.5

# Clear the console before starting
  clear

# Location
  export DIR=`readlink -f .`;

# Color
  On_Blue=`echo -e "\033[44m"`        # On Blue
  Red=`echo -e "\033[0;31m"`          # Red
  Blue=`echo -e "\033[0;34m"`         # Blue
  Color_Off=`echo -e "\033[0m"`       # Text Clear

# Check local and online version
  online_version=$(wget -qO- "https://forum.xda-developers.com/showthread.php?t=2073775" | cat | grep "AIK-Linux-v" | cut -d'-' -f4 | grep -oE 'v+[0-9]+.+[0-9]');
  if [[ -f $DIR/AIK-Linux-version ]]; then
    local_version=($(cat AIK-Linux-version 2>/dev/null));
  fi

downloadaik() {
  delete=($(ls *.sh *.txt AIK-Linux-version 2>/dev/null))
  for f in "${delete[@]}"; do
    rm -rf $DIR/$f
  done
  rm -rf $DIR/bin
  fname=aik.tar.gz
  furl=$(wget -qO- "https://forum.xda-developers.com/showthread.php?t=2073775" | cat | grep "AIK-Linux-v" | cut -d'"' -f2 | grep http | head -1)
  echo "Downloading $fname"
  (wget -O "$fname" "$furl" 2>&1) >/dev/null
  echo "Extracting $fname"
  tar -xf $DIR/$fname 2>&1 >/dev/null
  mv $DIR/AIK-Linux/* $DIR
  echo "Cleaning up files"
  if [[ -e $DIR/$fname && -d $DIR/AIK-Linux ]]; then
    rm -rf $DIR/$fname $DIR/AIK-Linux
  fi
  echo $online_version > $DIR/AIK-Linux-version
  echo "Done"
}

chooseimg() {
  findimg=""
  findimg=($(ls *.img *.elf *.win *.sin 2>/dev/null))
  declare -i i=1
  shift 2
  for e in "${findimg[@]}"; do
    echo "$i) $e"
    i=i+1
  done
  echo ""
  read -p "Select: " REPLY
  i="$REPLY"
  if [[ $i -gt 0 && $i -le ${#findimg[@]} ]]; then
    if [[ -e $DIR/image-new.img && "${findimg[$i-1]}"=="image-new.img" && ("$enterLetter" == "u" || "$enterLetter" == "U") ]]; then
      read -p "${Red}Rename image-new.img and try again!, Press ENTER to return to Main menu.${Color_Off}"
      $DIR/menu
    else
      export v="${findimg[$i-1]}"
    fi
  else
    read -p "${Red}Invalid option, Press ENTER to return to Main menu.${Color_Off}"
    $DIR/menu
  fi
}

choosepart() {
  declare -i i=1
  shift 2
  findpart=""
  findpart=(boot kernel ramdisk recovery recovery_ramdisk)
  for e in "${findpart[@]}"; do
    echo "$i) $e"
    i=i+1
  done
  echo ""
  read -p "Select: " REPLY
  i="$REPLY"
  if [[ $i -gt 0 && $i -le ${#findpart[@]} ]]; then
    export w="${findimg[$i-1]}"
  else
    read -p "${Red}Invalid option, Press ENTER to return to Main menu.${Color_Off}"
    $DIR/menu
  fi
}

# Menu
  echo "${On_Blue}AIK-Linux menu${Color_Off}"
  echo " "
if [[ ! -d $DIR/bin || ! -f $DIR/cleanup.sh || ! -f $DIR/repackimg.sh || ! -f $DIR/unpackimg.sh ]]; then
  echo " d. Download AIK-Linux"
else
  echo " u. Unpack *.img, *.elf, *.win or *.sin"
  echo " n. Unpack *.img, *.elf, *.win or *.sin without --nosudo"
  echo " r. Repack"
  echo " c. Cleanup"
  echo " "
  echo " f. fastboot flash *.img, *.elf, *.win or *.sin"
  echo " s. fastboot reboot"
  echo " a. adb reboot"
if [[  "$local_version" != "$online_version" ]]; then
  echo " d. Update AIK-Linux"
fi
fi
  echo " "
  echo " z. Restart menu"
  echo " x. Exit menu"
  echo " "
# Read the letter the user gives
  read  -p "Select: " enterLetter
  echo " "

# Unpack
  if [[ "$enterLetter" == "u" || "$enterLetter" == "U" ]]; then
    chooseimg
    $DIR/unpackimg.sh --nosudo $v
    read -p "${Blue}Press ENTER to return to Main menu.${Color_Off}"
    $DIR/menu

# Unpack without --nosudo
  elif [[ "$enterLetter" == "n" || "$enterLetter" == "N" ]]; then
    chooseimg
    $DIR/unpackimg.sh $v
    sudo chmod -R 777 $DIR/ramdisk
    read -p "${Blue}Press ENTER to return to Main menu.${Color_Off}"
    $DIR/menu

# Repack
  elif [[ "$enterLetter" == "r" || "$enterLetter" == "R" ]]; then
    $DIR/repackimg.sh
    read -p "${Blue}Press ENTER to return to Main menu.${Color_Off}"
    $DIR/menu

# Cleanup
  elif [[ "$enterLetter" == "c" || "$enterLetter" == "C" ]]; then
    $DIR/cleanup.sh
    read -p "${Blue}Press ENTER to return to Main menu.${Color_Off}"
    $DIR/menu

# fastboot flash
  elif [[ "$enterLetter" == "f" || "$enterLetter" == "F" ]]; then
    chooseimg
    choosepart
    fastboot flash $w $DIR/$v
    read -p "${Blue}Press ENTER to return to Main menu.${Color_Off}"
    $DIR/menu

# fastboot reboot
  elif [[ "$enterLetter" == "s" || "$enterLetter" == "S" ]]; then
    fastboot reboot
    read -p "${Blue}Press ENTER to return to Main menu.${Color_Off}"
    $DIR/menu

# adb reboot
  elif [[ "$enterLetter" == "a" || "$enterLetter" == "A" ]]; then
    adb reboot
    read -p "${Blue}Press ENTER to return to Main menu.${Color_Off}"
    $DIR/menu

# Download AIK-Linux
  elif [[ "$enterLetter" == "d" || "$enterLetter" == "D" ]]; then
    downloadaik
    read -p "${Blue}Press ENTER to return to Main menu.${Color_Off}"
    $DIR/menu

# Restart
  elif [[ "$enterLetter" == "z" || "$enterLetter" == "Z" ]]; then
    echo "Restarting menu"
    $DIR/menu

# Exit
  elif [[ "$enterLetter" == "x" || "$enterLetter" == "x" ]]; then
    echo "Exiting menu"
    exit 0

# Other choice
  else
    read -p "${Red}Invalid option, Press ENTER to return to Main menu.${Color_Off}"
    $DIR/menu
  fi
